kind: pipeline
type: kubernetes
name: test

steps:
  - name: install
    image: python:3.9-slim
    volumes: &cache-volume
      - name: pip-cache
        path: /root/.local
      - name: poetry-cache
        path: /root/.cache
    commands:
      - pip install --user --no-warn-script-location poetry
      - python -m poetry install

  - name: flake8
    image: python:3.9-slim
    volumes: *cache-volume
    commands:
      - python -m poetry run flake8 .
    depends_on:
      - install

  - name: mypy
    image: python:3.9-slim
    volumes: *cache-volume
    commands:
      - python -m poetry run mypy src
    depends_on:
      - install

  - name: publish
    image: python:3.9-slim
    volumes: *cache-volume
    environment:
      POETRY_HTTP_BASIC_BUZZVIL_USERNAME:
        from_secret: pypi_username
      POETRY_HTTP_BASIC_BUZZVIL_PASSWORD:
        from_secret: pypi_password
    commands:
      - python -m poetry config repositories.buzzvil http://pypi.buzzvil-internal.com/
      - python -m poetry publish --repository buzzvil --build
    depends_on:
      - flake8
      - mypy
    when:
      branch:
        - master
      event:
        - tag

volumes:
  - name: pip-cache
    temp: {}
  - name: poetry-cache
    temp: {}

trigger:
  ref:
    - refs/heads/master
    - refs/pull/**
    - refs/tags/v*