kind: pipeline
type: kubernetes
name: flake8

steps:
  - name: flake8
    image: zapier/python
    commands:
      - poetry install
      - poetry run flake8 .

trigger:
  event:
    - pull_request

---
kind: pipeline
type: kubernetes
name: mypy

steps:
  - name: mypy
    image: zapier/python
    commands:
      - poetry install
      - poetry run mypy src

trigger:
  event:
    - pull_request


---
kind: pipeline
type: kubernetes
name: publish

steps:
  - name: publish
    image: zapier/python
    environment:
      POETRY_HTTP_BASIC_BUZZVIL_USERNAME:
        from_secret: pypi_username
      POETRY_HTTP_BASIC_BUZZVIL_PASSWORD:
        from_secret: pypi_password
    commands:
      - poetry config repositories.buzzvil http://pypi.buzzvil-internal.com/
      - poetry publish --repository buzzvil --build

trigger:
  branch:
    - master
  event:
    - tag
