kind: pipeline
type: kubernetes
name: test

steps:
  - name: install
    image: python:3.9-slim
    volumes: &cache-volume
      - name: cache
        path: /root/.local
    commands:
      - pip install poetry

  - name: flake8
    image: python:3.9-alpine
    volumes: *cache-volume
    commands:
      - poetry run flake8 .
    depends_on:
      - install

  - name: mypy
    image: python:3.9-alpine
    volumes: *cache-volume
    commands:
      - poetry run mypy src
    depends_on:
      - install

  - name: publish
    image: python:3.9-alpine
    volumes: *cache-volume
    environment:
      POETRY_HTTP_BASIC_BUZZVIL_USERNAME:
        from_secret: pypi_username
      POETRY_HTTP_BASIC_BUZZVIL_PASSWORD:
        from_secret: pypi_password
    commands:
      - poetry config repositories.buzzvil http://pypi.buzzvil-internal.com/
      - poetry publish --repository buzzvil --build
    depends_on:
      - flake8
      - mypy
    when:
      branch:
        - master
      event:
        - tag

volumes:
  - name: cache
    temp: {}

trigger:
  ref:
    - refs/heads/master
    - refs/pull/**