["pyproject.toml".tool.black]
line-length = 120
skip-string-normalization = true
exclude = """
(
  /(
      .eggs
    | .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | /migrations/
  | venv*
)
"""