["pyproject.toml".tool.black]
line-length = 120
target-version = ['py27', 'py37', 'py38']
include = '\.pyi?$'
skip-string-normalization = true
exclude = """
(
  /(
      .eggs
    | .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | /migrations/
  | venv*
)
"""