["setup.cfg".flake8]
ignore = "W503,E203,FI58,PT003,C408,C400,C401"

max-line-length = 120
require-code = true

exclude = "venv*,**/migrations/"
per-file-ignores = "tests/**.py:FI18,CFQ001,E501,S101,FKA100,__init__.py:F401"

# flake8-functions
max-parameters-amount = 10
# flake8-annotations-complexity
max-annotations-complexity = 4
# flake8-pytest-style
pytest-parametrize-values-type = 'tuple'
eradicate-whitelist = 'mypy:#noqa:'
# flake8-force-keyword-arguments
kwargs-max-positional-arguments = 2

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude", "flake8.per-file-ignores"]