# coding: UTF-8

import ast

from typing import ClassVar, Deque, Iterable, Text, Tuple, Type

class FuncCallVisitor(ast.NodeVisitor):
    _name: Deque[Text]
    def __init__(self) -> None: ...
    @property
    def name(self) -> Text: ...
    @name.deleter
    def name(self) -> None: ...

class RequestsTimeoutPlugin(object):
    name: ClassVar[Text] = ...
    version: ClassVar[Text] = ...
    tree: ast.AST
    def __init__(self, tree: ast.AST) -> None: ...
    def run(self) -> Iterable[Tuple[int, int, Text, Type[RequestsTimeoutPlugin]]]: ...
